
server:
  port: 8082
spring:
  application:
    name: service-lease
    #JPA configure mysql路径，用户名、密码 以及驱动类
  cloud:
    gateway:
      routes:
      - id: host_route
        uri: http://localhost:8082/demo
        predicates:
        - Path=/a/** # 请求地址携带a的，则转发
        filters:
        - StripPrefix= 1 #截取/a/之后的路径